baseURL = "https://jadonsblog.com/"
languageCode = "en-us"
title = "Jadon Lawson"
theme = "hello-friend-ng"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  author = "Jadon Lawson"
  description = ""
  themeStyle = "dark"
  defaultTheme = "dark"
  enableThemeToggle = true
  enableSharingButtons = false
  enableGlobalLanguageMenu = false
  footerText = ""
  logoText = "home"
  customCSS = ["css/custom.css"]

[[params.social]]
  github = "https://github.com/ghostoptimizer"
  email = "mailto:jslawson2025@gmail.com"
  linkedin = "https://linkedin.com/in/jadonlawson"

[menu]
[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 1

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
