name: Publish Hugo site

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v4
        with:
          hugo-version: '0.115.1'

      - name: Build
        run: hugo -d public

      - name: Deploy via rsync over SSH
        uses: burnett01/rsync-deployments@v4
        with:
          switches: -avz --delete
          path: public/
          remote_host: ${{ secrets.DROPLET_HOST }}
          remote_user: webdeploy
          remote_path: /var/www/releases
          ssh_private_key: ${{ secrets.DEPLOY_KEY }}

      - name: Flip current symlink
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: webdeploy
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            # Determine the most recent release folder
            LATEST=$(ls -1 /var/www/releases | sort | tail -n1)
            ln -sfn /var/www/releases/$LATEST /var/www/current
